name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Verify Quarkus Extension with Maven
        run: mvn --batch-mode license:check verify
        env:
          API_KEY: ${{ secrets.TMDB_API_KEY }}
      - name: Read library version
        id: version_property
        run: echo "::set-output name=value::$(grep -o -P -e '<version>\K(\d+\.?)+(-SNAPSHOT)?' pom.xml | head -n1)"
      - name: Import GPG secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_SIGNING_SECRET_KEY_RING_BASE64 }}") | base64 -d - | gpg --batch --import
          gpg --list-secret-keys --keyid-format SHORT
      - name: Publish to Central Repository
        # if: ${{ !endsWith(steps.version_property.outputs.value, '-SNAPSHOT') }}
        run: mvn --batch-mode --settings .github/mvn-settings.xml clean deploy -P release
        env:
          API_KEY: ${{ secrets.TMDB_API_KEY }}
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
          SIGNING_PASSWORD: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.OSSRH_SIGNING_KEY_ID }}
